name: Docker Image CI

on:
  push:
    branches: [ "mqin" ]
  pull_request:
    branches: [ "mqin" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t my-app .

      - name: Run pythoncode_one.py
        run: docker run --rm my-app python3 pythoncode_one.py
        
